server:
  port: 9090

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
  
zuul:
  ignoredServices: '*'
  routes:
    products:
      path: /products/**
      stripPrefix: true
      serviceId: products-service

spring:
  application:
    name: zuul-server
    
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 15000
            
products-service:
  ribbon:
    ReadTimeout: 15000